📝 rename googlepalmapi.md to googlegeminiapi.md
continuedev/continue pull request #1174
Opened 2024-04-23 17:19 UTC by pzaback

## Description

Renamed doc file and all references to it from Palm to Gemini

## Checklist

- [x] The base branch of this PR is `preview`, rather than `main`

2024-04-23 19:06 UTC, sestinj requested changes

2024-04-23 19:06 UTC, sestinj commented on docs/docs/model-setup/select-provider.md
> +- [Google Gemini API](../reference/Model%20Providers/googlegeminiapi.md)
Only thing to add to this PR is we need to make sure that the docs page here exists. In `docs/docs/reference/Model Providers` can you change `googlepalmapi.md` to this new name? (actually I might choose just the name "gemini" while we're changing things, but having the page exist is the important part : ))

2024-04-23 21:19 UTC, pzaback commented on docs/docs/model-setup/select-provider.md
> +- [Google Gemini API](../reference/Model%20Providers/googlegeminiapi.md)
Ah geez, silly omission. I had actually renamed the file first through GH web interface but then couldn't figure out how to quickly update links in different files in the same commit so I just started over in local repo but forgot that repo-wide find/replace wouldn't include updating the filename itself. 😆

2024-04-24 05:40 UTC, sestinj commented on docs/docs/model-setup/select-provider.md
> +- [Google Gemini API](../reference/Model%20Providers/googlegeminiapi.md)
All good! And thanks for the rename to geminiapi. If you don't mind...I'm going to attempt to wait just a bit on merging because we deploy docs from the main branch, and I'd like to only release these links into the wild once the page they point to actually exists. So that should be this Friday that I plan for another main release

2024-04-24 14:20 UTC, pzaback commented on docs/docs/model-setup/select-provider.md
> +- [Google Gemini API](../reference/Model%20Providers/googlegeminiapi.md)
No rush from my end whatsoever. Aside from this being a minor thing I happened to stumble across  after seeing that the corresponding provider module was recently deleted, in general I have no desire to pressure merging of my PRs.

2024-05-03 21:22 UTC, merged