Consolidate example configurations into the main configuration guide
continuedev/continue pull request #1579
Opened 2024-06-26 16:44 UTC by priyashpatil

## Description

- Moved examples to configuration.md
- Deleted the separate examples.md file
- Updated sidebar order and links
- Improved readability and structure in configuration.md

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [x] The relevant docs, if any, have been updated or created

2024-06-26 20:09 UTC, Patrick-Erichsen requested changes
@priyashpatil thanks for submitting this! I think this is simpler & cleaner. I had just a few small suggestions and then I think this is good to merge

2024-06-26 20:09 UTC, Patrick-Erichsen commented on docs/docs/setup/configuration.md
> +This configuration leverages Ollama for all functionalities—chat, autocomplete, and embeddings—ensuring that no code is transmitted outside your machine.
```suggestion
This configuration leverages Ollama for all functionalities - chat, autocomplete, and embeddings - ensuring that no code is transmitted outside your machine.
```

2024-06-26 20:09 UTC, Patrick-Erichsen commented on docs/docs/setup/configuration.md
> +> Note: This example uses a free trial for embeddings and reranking, forwarding requests via ContinueDev proxy. For direct service, get a Voyage AI API key and update the `provider` and `apiKey` fiel
I think using an [admonition](https://docusaurus.io/docs/markdown-features/admonitions) here would be nice.

```suggestion
:::note

This example uses a free trial for embeddings and reranking, forwarding requests via ContinueDev proxy. For direct service, get a Voyage AI API key and update the `provider` and `apiKey` fields. See config reference for details.

:::
```

2024-06-27 07:31 UTC, priyashpatil commented
> @priyashpatil thanks for submitting this! I think this is simpler & cleaner. I had just a few small suggestions and then I think this is good to merge

@Patrick-Erichsen Good to go.

2024-06-27 13:35 UTC, Patrick-Erichsen commented on docs/docs/setup/configuration.md
> +  }
@sestinj - I am wondering if we want to encourage users to set up Voyage AI here rather than using the free trial. This would prevent users from having to come back and setup the Voyage provider once they've used their free trial credits.

2024-06-27 13:44 UTC, Patrick-Erichsen approved these changes

2024-06-27 15:05 UTC, merged