first commit
continuedev/continue pull request #1844
Opened 2024-07-26 20:43 UTC by samir-abis-everest

2024-07-26 21:29 UTC, sestinj requested changes

2024-07-26 21:29 UTC, sestinj commented on gui/src/components/mainInput/TipTapEditor.tsx
> +        const clipboardText = await navigator.clipboard.readText();
We are using execCommand because navigator.clipboard methods didn't correctly override the VS Code shortcuts as we needed for ipynbs. If this is reverted back everything else looks great

2024-07-27 10:14 UTC, samirabis commented on gui/src/components/mainInput/TipTapEditor.tsx
> +        const clipboardText = await navigator.clipboard.readText();
done

2024-07-27 10:14 UTC, samir-abis-everest commented on gui/src/components/mainInput/TipTapEditor.tsx
> +        const clipboardText = await navigator.clipboard.readText();
done

2024-07-30 20:01 UTC, merged

2024-07-30 20:01 UTC, sestinj commented
Thanks for the great contribution @samir-abis-everest !