feat: Add Text-to-Speech
continuedev/continue pull request #2012
Opened 2024-08-14 17:15 UTC by mkummer225

## Description

This PR adds text-to-speech functionality using built-in, system TTS programs ("say ...", "espeak ...", etc).

It can be enabled via `experimental.readResponseTTS` in continue's config.json

TTS should work for OSX, Windows, and linux where `espeak` is available – this PR still needs testing on Windows and Linux to confirm their implementations.

When enabled, TTS will start after the full chat has been streamed. It will skip reading code blocks and only read the top level text response. When initiating a new chat it will automatically stop any current TTS. Additionally, there's a button added to the bottom of the sidebar (shown below) to manually stop TTS.

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [ ] The relevant docs, if any, have been updated or created

## Screenshots

<img width="626" alt="image" src="https://github.com/user-attachments/assets/8f5cb174-ac70-4b2d-9db4-72994f9ecc18">

_A `Stop TTS` button has been added to the bottom of the sidebar while TTS is active. Clicking the button will stop the current TTS_

## Testing

Pull and debug this branch then set `experimental.readResponseTTS` to `true` in your config. Initiate a new chat with an LLM and after receiving the full response it should start reading aloud using your system's TTS capabilities.

2024-08-15 23:07 UTC, sestinj requested changes
@mkummer225 this is so cool! Small comments, let me know what you think. Very glad to see that you designed this so that it's open for extensibility with other providers

2024-08-15 23:07 UTC, sestinj commented on gui/src/redux/slices/stateSlice.ts
> +    setTTSInactive: (state) => {
And then same here, these can be merged into a single redux action

2024-08-15 23:07 UTC, sestinj commented on core/protocol/webview.ts
> +  setTTSActive: [undefined, void];
Can we change this to `setTTSActive: [boolean, void]` so that there's only one of them?

2024-08-15 23:07 UTC, sestinj commented on core/config/profile/doLoadConfig.ts
> +  // TODO: pass config to pre-load non-system TTS models
love this

2024-08-20 04:51 UTC, mkummer225 reviewed
changes made

2024-08-23 01:36 UTC, sestinj approved these changes

2024-08-23 01:36 UTC, sestinj commented
Congrats on PR number 1!

2024-08-23 01:36 UTC, merged