Pieces x continue
continuedev/continue pull request #2282
Opened 2024-09-17 09:55 UTC by sambhavnoobcoder

## Description
Added support for Pieces OS as a new LLM provider in Continue. This integration allows users to utilize Pieces OS for completions and other supported operations within the Continue environment.

## Checklist
- [ ] The base branch of this PR is `dev`, rather than `main`
- [x] The relevant docs have been created and updated

## Details of Changes
1. Created `piecesOSLLM.ts` in the `core/llm/llms` directory
2. Implemented `PiecesOSLLM` class extending `BaseLLM`
3. Set up PiecesOS provider and client
4. Implemented key methods: `_convertArgs`, `_streamComplete`, `_call`
5. Added getters for LLM type and identifying parameters
6. Updated `index.ts` to include PiecesOS
7. Updated `config_schema.json` for PiecesOSLLM configuration
8. Created `piecesOSLLM.md` documentation
9. Added setup instructions, configuration details, usage guidelines, and limitations

## Testing
To test this new LLM provider:

1. Install Pieces OS locally on your machine.
2. Ensure the Pieces OS API server is running on your local machine (typically on port 1000).
3. Update your `~/.continue/config.json` file with the Pieces OS configuration as described in the documentation.
4. Start Continue and attempt to use Pieces OS as you would any other model provider.
5. Verify that completions and other supported operations work as expected through the Pieces OS API.

2024-09-17 10:17 UTC, shivay-couchbase commented
@sestinj could you share your thoughts regarding this

2024-09-17 16:19 UTC, sestinj requested changes
Just a few small comments, generally looks good

2024-09-17 16:19 UTC, sestinj commented on core/llm/llms/piecesOSLLM.ts
> +    model: "pieces_os",
Can we use "pieces-os" everywhere instead to match casing?

2024-09-17 16:19 UTC, sestinj commented on docs/docs/customize/model-providers/more/piecesOSLLM.md
> +      "apiBase": "http://localhost:1000"
If this is the default it shouldn't be necessary for users to configure

2024-09-17 16:19 UTC, sestinj commented on core/llm/llms/piecesOSLLM.ts
> +  protected async *_streamComplete(
Does Pieces OS have a way of handling chat input?

2024-09-17 18:03 UTC, sambhavnoobcoder commented on core/llm/llms/piecesOSLLM.ts
> +    model: "pieces_os",
resolved it in a75becd , a84de6e , [3601849](https://github.com/continuedev/continue/pull/2282/commits/36018494ebb92bd22548ac4df6c34082f32cc27e) commits

2024-09-17 18:07 UTC, sambhavnoobcoder commented on docs/docs/customize/model-providers/more/piecesOSLLM.md
> +      "apiBase": "http://localhost:1000"
resolved issue in commit [56a5ad4](https://github.com/continuedev/continue/pull/2282/commits/56a5ad4fe319bbe649f9fcb16fa79c26ea153ea8)

2024-09-17 21:58 UTC, sambhavnoobcoder commented on core/llm/llms/piecesOSLLM.ts
> +  protected async *_streamComplete(
@sestinj  could you elaborate on what you mean by handling chat input ? Also could you potentially list or point to some other code in the repo where this is done as intended?

2024-09-24 13:53 UTC, sambhavnoobcoder commented on core/llm/llms/piecesOSLLM.ts
> +  protected async *_streamComplete(
@sestinj  .

2024-09-29 02:27 UTC, sestinj commented
Hi @sambhavnoobcoder—sorry for the delay. I'm looking into Pieces OS more and thinking that something even better than this PR might be OpenAI-compatibility so that a custom provider isn't needed. We're reaching a point where there are such a large number of LLM providers to maintain that it is likely to cause many of them to fall out of regular maintenance. The more providers can use OpenAI-compatible servers, the more stable and up-to-date support we can offer for them, and I'd strongly prefer to do this for Pieces.

Is Pieces OS OpenAI-compatible, or is this a change that could be made? I would estimate that this would require fewer lines of code within PiecesOS than it would in this current PR

2024-10-02 09:32 UTC, Thompson1985 reviewed
Thank you

2024-10-02 17:19 UTC, Thompson1985 reviewed
Thank you

2024-10-13 06:41 UTC, sestinj commented
Hi @sambhavnoobcoder, since it's been a while and I think that the OpenAI-compatibility approach would be much better, I'm going to close this PR for the time being. Happy to take another look if you have the chance to look into the OpenAI-compatible route

2024-10-13 06:41 UTC, closed without merging