Added discord context provider
continuedev/continue pull request #2425
Opened 2024-09-30 03:57 UTC by eagle3y3

## Description

I've added a discord provider. Currently it is able to read text channels. It must be installed with a bot on the server. I think it would be a very useful bridge from devs to users who like to communicate through Discord. In order to test and run it. You must have a bot token and the same bot installed onto your server. Reading threads will come soonish if there's any interest.

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [x] The relevant docs, if any, have been updated or created

## Screenshots

![Code_ypqBbF3aco](https://github.com/user-attachments/assets/8cb02d1e-bfdc-4a32-92b2-84b69b44def3)

## Testing

[ For new or modified features, provide step-by-step testing instructions to validate the intended behavior of the change. ]

2024-10-04 23:44 UTC, sestinj requested changes
Overall, love it! Good to go after changing to fetch

2024-10-04 23:44 UTC, sestinj commented on core/context/providers/DiscordContextProvider.ts
> +import axios, { AxiosInstance } from "axios";
I know this looks a bit nit-picky, but can this be swapped for `fetch` rather than `axios`? We have standardized across the codebase with this, and it will allow you to use the injected version of fetch that inherits global `requestOptions` from `config.json`

2024-10-07 04:54 UTC, eagle3y3 commented on core/context/providers/DiscordContextProvider.ts
> +import axios, { AxiosInstance } from "axios";
Done 😃! Just swapped axios for fetch.

2024-10-13 04:52 UTC, sestinj approved these changes

2024-10-13 04:52 UTC, merged

2025-05-15 18:05 UTC, sestinj commented
Hi @eagle3y3, yesterday we shared [some updates](https://discordapp.com/channels/1108621136150929458/1131313996750917835/1371996789967687783) with our contributors about how we're aiming to improve the contribution process. Part of this included the addition of a [Contributor License Agreement](https://github.com/continuedev/continue/blob/main/docs/docs/CLA.md) (CLA) to protect both contributors and the project. We're reaching out to ask that previous contributors sign it.

Could you please take a moment to sign, or if you have any questions send me a message? (either here or nate@continue.dev would work)

To do so, you just need to **post a comment below with the following text:**<br/>
```
I have read the CLA Document and I hereby sign the CLA
```

❤️ Thank you for the work you've done on Continue, and let me know if you have any suggestions on how we can make the project even better!

2025-06-20 19:57 UTC, eagle3y3 commented
Hey Nate, sure. I have read the CLA Document and I hereby sign the CLA.