feat: Automatic Chat Titles
continuedev/continue pull request #2468
Opened 2024-10-04 20:15 UTC by mkummer225

## Description

This PR adds automatic title generation for chat sessions. Currently it runs after the user submits their first chat (there's an opportunity for more robust logic added here). We piggy back off the user's currently selected model while limiting the maxTokens (response tokens) to 24; the baked-in prompt asks the model to reply with 4-12 words.

Currently this feature is enabled using the experimental config parameter: `getChatTitles: boolean;`

There appears to have been a prior effort to add this functionality via the `disableSessionTitles` config param (enabled by default then the user could opt-out). When this feature is ready to come out of experimental we should clean up this prior param (assuming I understood it's purpose correctly)

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [ ] The relevant docs, if any, have been updated or created

## Screenshots

No visual changes were made; the titles are shown the same as before

<img width="552" alt="image" src="https://github.com/user-attachments/assets/92b79016-676a-41ea-b7f1-d973025f33e2">

<img width="563" alt="image" src="https://github.com/user-attachments/assets/cb45c273-acc6-4b1a-b68e-039170f9c173">

## Testing

Enable this feature by setting `experimental.getChatTitles` to `true`

2024-10-04 20:24 UTC, mkummer225 commented
While building this feature I spent a decent amount of time thinking about ways to improve search & organization of past chats – it might be cool to have a set of tags that the LLM also generates when generating the title. Then in the history tab the user is able to click-select multiple tags while filtering.

2024-10-04 23:59 UTC, sestinj requested changes
Excellent work overall! The two comments are fairly crucial imo, but happy to merge after that

2024-10-04 23:59 UTC, sestinj commented on core/core.ts
> +      if (config.experimental?.getChatTitles && "completion" in next.value && msg.data.messages.filter(m => m.role === "user").length === 1) {
Initiation of the request for the description should happen from the GUI. We may wish to use llmStreamChat for various reasons other than literally a chat session message, and wouldn't want this spending tokens in those cases.

This warrants a new core protocol message type, which can then be called directly from the GUI

2024-10-04 23:59 UTC, sestinj commented on core/util/chatDescriber.ts
> +    ChatDescriber.messenger?.send("setCurrentChatTitle", titleResponse.content.toString());
i'd recommend trimming the response and removing quotes. I believe we already have utilities for stripping quotes from last time in core/util somewhere

2024-10-05 19:51 UTC, mkummer225 commented on core/core.ts
> +      if (config.experimental?.getChatTitles && "completion" in next.value && msg.data.messages.filter(m => m.role === "user").length === 1) {
Yeah that definitely makes sense!

2024-10-05 20:27 UTC, mkummer225 commented on core/core.ts
> +      if (config.experimental?.getChatTitles && "completion" in next.value && msg.data.messages.filter(m => m.role === "user").length === 1) {
Updated execution to be housed within useHistory's `saveSession` method and removed `setCurrentChatTitle` in favor of directly returning the string value when invoking `chatDescriber/describe`

2024-10-05 20:32 UTC, mkummer225 commented on core/util/chatDescriber.ts
> +    ChatDescriber.messenger?.send("setCurrentChatTitle", titleResponse.content.toString());
updated

2024-10-13 06:00 UTC, merged

2024-10-13 06:00 UTC, sestinj commented
great work!

2025-05-15 18:05 UTC, sestinj commented
Hi @mkummer225, yesterday we shared [some updates](https://discordapp.com/channels/1108621136150929458/1131313996750917835/1371996789967687783) with our contributors about how we're aiming to improve the contribution process. Part of this included the addition of a [Contributor License Agreement](https://github.com/continuedev/continue/blob/main/docs/docs/CLA.md) (CLA) to protect both contributors and the project. We're reaching out to ask that previous contributors sign it.

Could you please take a moment to sign, or if you have any questions send me a message? (either here or nate@continue.dev would work)

To do so, you just need to **post a comment below with the following text:**<br/>
```
I have read the CLA Document and I hereby sign the CLA
```

❤️ Thank you for the work you've done on Continue, and let me know if you have any suggestions on how we can make the project even better!