feat: Add SageMaker Embeddings
continuedev/continue pull request #2469
Opened 2024-10-04 20:39 UTC by kbreese-x

## Description

This pull request adds SageMaker as an embeddings model provider. The new provider is primarily designed to work with SageMaker endpoints deployed using the Huggingface TEI containers, but can be customized to work with other endpoints too through the use of `requestOptions.extraBodyProperties`. Documentation on how to set up the new provider has been added to both the Embedding Models and Sagemaker Provider pages. The config_schema has been updated for both vscode and intellij to include `sagemaker` as a new provider, as well as providing some default region options for the most commonly used AWS regions.

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [x] The relevant docs, if any, have been updated or created

## Screenshots

[ For visual changes, include screenshots. ]

## Testing

Requires: AWS Sagemaker endpoint deployed with TEI container (example [here](https://www.philschmid.de/sagemaker-train-deploy-embedding-models#4-deploy--test-fine-tuned-embedding-model-on-amazon-sagemaker))
Requires: an AWS profile called "sagemaker" or a default profile with permissions to invoke endpoints

Add the following configuration:
"embeddingsProvider": {
    "provider": "sagemaker",
    "model": "embedding-test-endpoint",
    "maxBatchSize": 12,
    "profile": "default",
    "region": "us-west-2",
    "requestOptions": {
      // this is an example for an endpoint deployed using TEI
      "extraBodyProperties": {
        "parameters": {
          "truncate": true
        }
      }
    }

To learn more about the parameters you can send to TEI backed endpoints, see the API reference [here](https://huggingface.github.io/text-embeddings-inference/#/Text%20Embeddings%20Inference/embed)

2024-10-05 00:03 UTC, sestinj requested changes
minor comments then good to go—thank you for this!

2024-10-05 00:03 UTC, sestinj commented on docs/docs/customize/model-types/embeddings.md
> +
I think SageMaker is a bit more niche so I would prefer it not exist in this list here (we also leave out a number of other embeddings providers)

2024-10-05 00:03 UTC, sestinj commented on extensions/vscode/config_schema.json
> +              "enum": [
Can this be made a variable?

2024-10-05 02:10 UTC, kbreese-x commented
Done!
didn't move the region definition to top level since it seems minor, but just referenced it where needed

2024-10-05 02:14 UTC, kbreese-x commented on extensions/vscode/config_schema.json
> +              "enum": [
referenced later instead of duplicating

2024-10-09 01:37 UTC, sestinj approved these changes

2024-10-09 01:37 UTC, merged

2025-05-15 18:05 UTC, sestinj commented
Hi @kbreese-x, yesterday we shared [some updates](https://discordapp.com/channels/1108621136150929458/1131313996750917835/1371996789967687783) with our contributors about how we're aiming to improve the contribution process. Part of this included the addition of a [Contributor License Agreement](https://github.com/continuedev/continue/blob/main/docs/docs/CLA.md) (CLA) to protect both contributors and the project. We're reaching out to ask that previous contributors sign it.

Could you please take a moment to sign, or if you have any questions send me a message? (either here or nate@continue.dev would work)

To do so, you just need to **post a comment below with the following text:**<br/>
```
I have read the CLA Document and I hereby sign the CLA
```

❤️ Thank you for the work you've done on Continue, and let me know if you have any suggestions on how we can make the project even better!