Added Bedrock Cohere Embeddings Provider + explicit apache arrow as d…
continuedev/continue pull request #2478
Opened 2024-10-05 20:01 UTC by Anantha-Kandrapu

## Description

1. I added a Bedrock cohere embeddings provider. 
2. I had to add apache arrow as dependency because there were build issues without that package as vectorDB depends on it. (I pasted the error log in the issue).

## Checklist

- [ ] The base branch of this PR is `dev`, rather than `main`
- [ ] The relevant docs, if any, have been updated or created

## Screenshots

1. There's no visual changes.

## Testing
1) I have tested this change in debug mode as mentioned in the documentation, it was able to use bedrock cohere embedding model and fetch the results.
2) I ran the `npm run package` , copied the extension to another machine and tried it. It ran successfully.

2024-10-06 06:14 UTC, Anantha-Kandrapu commented
I will squash and merge.

2024-10-13 05:50 UTC, sestinj commented
@Anantha-Kandrapu thanks for the PR! It looks like a lot of the logic here might overlap with the original Bedrock provider—do you think that we could maintain just a single bedrock embeddings provider that can also support cohere?

2024-10-13 05:50 UTC, sestinj commented
Also, I would prefer if the adding of the dependency were in a separate PR, as I'll probably want to review that a bit more closely and it isn't strictly necessary for this update

2024-10-15 05:38 UTC, chezsmithy requested changes

2024-10-15 05:38 UTC, chezsmithy commented on core/indexing/embeddings/BedrockCohereEmbeddingsProvider.ts
> +        profile: this.profile
Check the most recent bedrock code and disable caching.

2024-10-19 07:09 UTC, Anantha-Kandrapu commented
> @Anantha-Kandrapu thanks for the PR! It looks like a lot of the logic here might overlap with the original Bedrock provider—do you think that we could maintain just a single bedrock embeddings provider that can also support cohere?

I have also added a interface so that multiple other embedding providers from bedrock can be added in future.

2024-10-20 01:18 UTC, chezsmithy approved these changes

2024-10-20 03:19 UTC, Anantha-Kandrapu commented
Hey @chezsmithy , Thanks for the approval earlier.
My fork was out of sync. There's one more approval I need. 
Thanks.

2024-10-24 19:16 UTC, merged

2024-10-24 19:16 UTC, Patrick-Erichsen commented
Thanks for the great work here @Anantha-Kandrapu !

2025-05-15 18:05 UTC, sestinj commented
Hi @Anantha-Kandrapu, yesterday we shared [some updates](https://discordapp.com/channels/1108621136150929458/1131313996750917835/1371996789967687783) with our contributors about how we're aiming to improve the contribution process. Part of this included the addition of a [Contributor License Agreement](https://github.com/continuedev/continue/blob/main/docs/docs/CLA.md) (CLA) to protect both contributors and the project. We're reaching out to ask that previous contributors sign it.

Could you please take a moment to sign, or if you have any questions send me a message? (either here or nate@continue.dev would work)

To do so, you just need to **post a comment below with the following text:**<br/>
```
I have read the CLA Document and I hereby sign the CLA
```

❤️ Thank you for the work you've done on Continue, and let me know if you have any suggestions on how we can make the project even better!