Full screen UI improvements
continuedev/continue pull request #2493
Opened 2024-10-08 15:09 UTC by tomasz-stefaniak

## Description

[ What changed? Feel free to be brief. ]

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [ ] The relevant docs, if any, have been updated or created

## Screenshots

[ For visual changes, include screenshots. ]

## Testing

[ For new or modified features, provide step-by-step testing instructions to validate the intended behavior of the change. ]

2024-10-08 16:12 UTC, Patrick-Erichsen commented on gui/src/context/LastSessionContext.tsx
> +    const storedId = localStorage.getItem("lastSessionId");
We have a file with typings for all of our localStorage accessors: https://github.com/continuedev/continue/blob/main/gui/src/util/localStorage.ts

So I think we should add this there and update to use the `getLocalStorage` fn.

2024-10-08 16:14 UTC, Patrick-Erichsen commented on gui/tailwind.config.cjs
> +      "2xs": "170px", // Smallest width for Primary Sidebar in VS Code
Thanks for making this update! 😁

2024-10-08 16:16 UTC, tomasz-stefaniak commented on gui/src/context/LastSessionContext.tsx
> +    const storedId = localStorage.getItem("lastSessionId");
It's already there 😄 I'm just reusing an already existing value 
![image](https://github.com/user-attachments/assets/357849a0-d54d-4e0d-bfa5-c238b118033f)

2024-10-08 16:40 UTC, tomasz-stefaniak commented on gui/src/context/LastSessionContext.tsx
> +    const storedId = localStorage.getItem("lastSessionId");
This code actually wasn't needed. Removed it 👌

2024-10-08 22:03 UTC, TyDunn requested changes
@tomasz-stefaniak Looks like a good next iteration! My two thoughts:
1. I suspect we'll want to increase the breakpoint a little, so that the history section is only added if the sidebar is expanded a bit wider than the current breakpoint
2. I think we should work on making the history page look / feel much nicer after we get this merged

2024-10-09 13:02 UTC, tomasz-stefaniak commented
> @tomasz-stefaniak Looks like a good next iteration! My two thoughts:
> 
> 1. I suspect we'll want to increase the breakpoint a little, so that the history section is only added if the sidebar is expanded a bit wider than the current breakpoint
> 2. I think we should work on making the history page look / feel much nicer after we get this merged

1. I updated it to 1180px from 1140px. I think it's the right balance - any wider and it wouldn't open at all unless the left bar is removed.
2. I agree - I wanted to get this PR out of the way quickly but there's plenty of room for improvement on the history page UI

2024-10-13 04:40 UTC, sestinj approved these changes

2024-10-13 04:40 UTC, merged