change: rename locals to debugger (#2503)
continuedev/continue pull request #2509
Opened 2024-10-12 12:49 UTC by hserranome

## Description

Change proposed in https://github.com/continuedev/continue/issues/2503#issuecomment-2408144695

Renamed "locals" to "debugger"
Renamed LocalsProvider to DebugLocalsProvided for better clarity
Updated descriptions to specify that "local variables" refers to the debugger

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [x] The relevant docs, if any, have been updated or created

## Screenshots

![Screenshot 2024-10-12 144848](https://github.com/user-attachments/assets/19401233-4bed-4857-8f81-f9df3181fa50)
![image](https://github.com/user-attachments/assets/b9ebb55d-e2d0-4199-8850-ec1bb98e30cb)

## Testing

Use the debugger context provider as if it were the locals provided

2024-10-13 05:47 UTC, sestinj requested changes
all looks good, name makes much more sense! just 2 changes

2024-10-13 05:47 UTC, sestinj commented on extensions/vscode/textmate-syntaxes/MagicPython.tmLanguage.json
> +          "match": "(?x)\n  (?<!\\.) \\b(\n    __import__ | abs | all | any | ascii | bin | callable\n    | chr | compile | copyright | credits | delattr | dir | divmod\n    | enumerate | eval | exec
this shouldn't be changed

2024-10-13 05:47 UTC, sestinj commented on core/context/providers/LocalsProvider.ts
>  } from "../../index.js";
can the name of this file also be changed?

2024-10-13 08:37 UTC, hserranome commented on extensions/vscode/textmate-syntaxes/MagicPython.tmLanguage.json
> +          "match": "(?x)\n  (?<!\\.) \\b(\n    __import__ | abs | all | any | ascii | bin | callable\n    | chr | compile | copyright | credits | delattr | dir | divmod\n    | enumerate | eval | exec
Yeah, got to eager with the find and replace. Fixed.

2024-10-13 08:37 UTC, hserranome commented on core/context/providers/LocalsProvider.ts
>  } from "../../index.js";
Yep. Done.

2024-10-13 22:44 UTC, zzulanas reviewed
Just putting my two cents in since I commented about the issue haha, haven't contributed (yet!) but was wondering if it's clearer to rename this for future development

2024-10-13 22:44 UTC, zzulanas commented on core/context/providers/DebugLocalsProvider.ts
> -class LocalsProvider extends BaseContextProvider {
❓ Hmmm would it be clearer to name this `DebuggerLocalsProvider`? Not sure if keeping it as "Debug" is clear that this is for debugger and not debug code.

2024-10-16 18:25 UTC, sestinj approved these changes

2024-10-16 18:25 UTC, merged

2024-10-19 07:57 UTC, Thompson1985 approved these changes

2025-05-15 18:05 UTC, sestinj commented
Hi @hserranome, yesterday we shared [some updates](https://discordapp.com/channels/1108621136150929458/1131313996750917835/1371996789967687783) with our contributors about how we're aiming to improve the contribution process. Part of this included the addition of a [Contributor License Agreement](https://github.com/continuedev/continue/blob/main/docs/docs/CLA.md) (CLA) to protect both contributors and the project. We're reaching out to ask that previous contributors sign it.

Could you please take a moment to sign, or if you have any questions send me a message? (either here or nate@continue.dev would work)

To do so, you just need to **post a comment below with the following text:**<br/>
```
I have read the CLA Document and I hereby sign the CLA
```

❤️ Thank you for the work you've done on Continue, and let me know if you have any suggestions on how we can make the project even better!