Added support for MSSQL to the DatabaseContextProvider
continuedev/continue pull request #2655
Opened 2024-10-24 07:55 UTC by DifferentialityDevelopment

## Description

I've added support for MSSQL to the DatabaseContextProvider, honestly just a few config tweaks were required.
The package dbinfoz that DatabaseContextProvider relies on has already been updated to support MSSQL.

## Checklist

- [ ] The base branch of this PR is `dev`, rather than `main`
- [ ] The relevant docs, if any, have been updated or created

## Screenshots

[ For visual changes, include screenshots. ]

## Testing

Install SQL Server
Ensure local connectivity to SQL Server
Update continue.dev config for @database context provider and add mssql connection paramaters.
Try out @database with the mssql server

2024-10-24 07:55 UTC, DifferentialityDevelopment commented
I closed my previous PR and instead made the changes on the dev branch.

2024-10-24 17:32 UTC, Patrick-Erichsen requested changes

2024-10-24 17:32 UTC, Patrick-Erichsen commented on docs/static/schemas/config.json
> +                "mssql",
```suggestion
```
What this would be doing is implying that there is a new context provider called "mssql" - however, what we're actually doing is adding a `connection_type` to the existing `database` context provider, so this line is not needed.

2024-10-24 17:33 UTC, Patrick-Erichsen commented on docs/static/schemas/config.json
> +                "mssql",
I can see the source of your confusion here though since we have a `postgres` provider in addition to the `database` provider.

I'm not actually sure why that's the case. Ideally we just have the single `database` provider.

@rootedbox @sestinj - any context here? Would it be possible to remove `postgres` and consolidate on a single `database` provider using "dbzinfo"?

2024-10-24 23:01 UTC, rootedbox commented on docs/static/schemas/config.json
> +                "mssql",
@Patrick-Erichsen we might want to remove the postgres provider as the database provider can do the same thing.. and more. What do you think?

2024-10-30 05:28 UTC, sestinj commented on docs/static/schemas/config.json
> +                "mssql",
Yes, I am generally in agreement. I believe they were contributed at a similar point in time. There are certainly people using the postgres provider so we'll probably want to either throw in a validation warning to help people migrate (in the new validation.ts)

2024-10-30 05:29 UTC, sestinj requested changes
It is my understanding from the thread above that we can leave this PR to just being the upgrade to dbinfoz?

2024-10-30 05:48 UTC, DifferentialityDevelopment commented
> It is my understanding from the thread above that we can leave this PR to just being the upgrade to dbinfoz?

Not entirely correct, the arguments for mssql is slightly different than for postgres, namely where postgres you pass 'host' argument, in mssql you pass 'server' argument instead, so a few of my changes were to add the necessary validation for it.

2024-11-10 08:36 UTC, sestinj approved these changes

2024-11-10 08:42 UTC, merged

2024-11-16 08:31 UTC, DifferentialityDevelopment commented
Hey there!

I've got the latest version installed, also tried release version but for some reason still shows "Unsupported database type" when trying to link up my local mssql db in my continue.dev config file.
Not sure how to go about fixing it, from what I can tell the dbinfoz package is indeed correct version in continue.dev's package.json ie 0.14.0.

Anyone have any idea how to fix it?

2024-11-16 08:56 UTC, DifferentialityDevelopment commented
![image](https://github.com/user-attachments/assets/67cf5c58-11dd-41b2-a750-cff644f3b9e6)
I opened up the installed extension folder and searched for dbinfo in the compiled code but cannot find the mssql adapter there.
But it does seem to be using dbinfoz package 0.14.0 so not sure what's going on.

2024-11-16 08:58 UTC, DifferentialityDevelopment commented
Perhaps the old code is being cached somehow during the workflow?
https://github.com/continuedev/continue/blob/main/.github/workflows/main.yaml

2024-11-16 08:59 UTC, DifferentialityDevelopment commented
Perhaps the old code is being cached somehow during the workflow?
https://github.com/continuedev/continue/blob/main/.github/workflows/main.yaml
@Patrick-Erichsen @rootedbox

2025-01-07 09:54 UTC, DifferentialityDevelopment commented
This has recently stopped working for whatever reason, when I find some time I'll try and figure out why it stopped working, but any help would be appreciated.