Add Nebius AI Studio LLM and embedding providers
continuedev/continue pull request #2710
Opened 2024-10-28 10:34 UTC by vadjs

## Description

Added Nebius AI Studio LLM and embedding provider.

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [x] The relevant docs, if any, have been updated or created

## Screenshots

No visual changes

## Testing

It's not a feature, it's a new provider. The testing is simple: User Nebius provider with their API key. It just works.

2024-10-30 00:46 UTC, RomneyDa requested changes

2024-10-30 00:46 UTC, RomneyDa commented on core/llm/llms/Nebius.ts
Hi @vadjs, nice addition, looks like Nebius is OpenAI compatible, could you switch this out for a simpler class that extends OpenAI? 

Kind of like:
https://github.com/continuedev/continue/blob/dev/core/llm/llms/Kindo.ts

or did I miss a reason for extending BaseLLM?

2024-10-30 05:08 UTC, sestinj requested changes
Thanks for the PR! I'd like to second the comment from Dallin: since it appears Nebius is OpenAI-compatible, I would prefer that this is just a subclass of the OpenAI class. I also noticed that the default base URL for the embeddings provider was a Voyage AI URL, I think this needs to be cleaned up

2024-10-30 17:19 UTC, vadjs commented on core/llm/llms/Nebius.ts
Hi @RomneyDa, thank you for your advise!
I've changed Nebius provider accordingly. Now it extends OpenAI.

2024-10-30 17:36 UTC, vadjs commented
Hi @sestinj,
Thank you for the good point. I've changed apiBase URL in the `NebiusEmbeddingsProvider` to the correct one.
Also extended `Nebius` LLM provider from `OpenAI` class as proposed before.

2024-10-31 19:14 UTC, sestinj approved these changes

2024-10-31 19:19 UTC, sestinj commented
Awesome, thank you!

2024-10-31 19:19 UTC, merged