support `Qwen/Qwen2.5-Coder-32B-Instruct` model provided by siliconflow
continuedev/continue pull request #2974
Opened 2024-11-18 09:52 UTC by AnoyiX

## Description

support some models provided by siliconflow, like 
- `Qwen/Qwen2.5-Coder-32B-Instruct`
- `Qwen/Qwen2.5-Coder-7B-Instruct`

## Testing

custom config:

```
{
  "models": [
    {
      "title": "Qwen2.5 Coder",
      "provider": "openai",
      "model": "Qwen/Qwen2.5-Coder-32B-Instruct",
      "apiKey": "************************************",
      "apiBase": "https://api.siliconflow.cn/v1/"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Qwen2.5 Coder",
    "provider": "openai",
    "model": "Pro/Qwen/Qwen2.5-Coder-7B-Instruct",
    "apiKey": "************************************",
    "apiBase": "https://api.siliconflow.cn/v1/"
  },
  ...
}
```

AI Edit Example:
<img width="1089" alt="image" src="https://github.com/user-attachments/assets/fae281cb-9e2e-4952-83ee-6b7ca6358969">

Autocomplete Example:
<img width="1089" alt="image" src="https://github.com/user-attachments/assets/54413057-7c90-4f99-949f-7b5e15204611">

2024-11-18 20:27 UTC, sestinj requested changes

2024-11-18 20:27 UTC, sestinj commented on core/llm/llms/OpenAI.ts
> +    const url = this.apiBase?.includes("api.siliconflow.cn") ? "completions" : "fim/completions"
@AnoyiX Can we make a dedicated `LLM` class instead of putting the logic in `OpenAI.ts`? A good example would be in `Deepseek.ts`, where we subclass `OpenAI` and adjust the FIM logic

2024-11-19 02:17 UTC, AnoyiX commented on core/llm/llms/OpenAI.ts
> +    const url = this.apiBase?.includes("api.siliconflow.cn") ? "completions" : "fim/completions"
It might be better to allow custom `endpoints`, there are so many providers, it’s hard to support them all, what do you think?

2024-11-20 06:02 UTC, sestinj commented on core/llm/llms/OpenAI.ts
> +    const url = this.apiBase?.includes("api.siliconflow.cn") ? "completions" : "fim/completions"
I think that's fine as long as they have the exact same expected request body. I would just make it a function like `getFimEndpoint` so that it can be modified by subclasses, and then make a subclass of the endpoint. I'm not worried about having a large number of subclasses

2024-11-20 06:10 UTC, AnoyiX commented on core/llm/llms/OpenAI.ts
> +    const url = this.apiBase?.includes("api.siliconflow.cn") ? "completions" : "fim/completions"
Sounds good. It's convenient for subclasses to implement `getFimEndpoint`, this way we can avoid duplicating a lot of code in `*_streamFim`

2024-11-21 10:01 UTC, AnoyiX commented on core/llm/llms/OpenAI.ts
> +    const url = this.apiBase?.includes("api.siliconflow.cn") ? "completions" : "fim/completions"
you can review the latest code ~ 😊

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/535ab566-0ff8-4a79-81ab-3f78306cbecf">

2024-11-22 05:07 UTC, sestinj commented on core/llm/llms/OpenAI.ts
> +    const endpoint = this.apiBase?.includes("completions") ? new URL(this.apiBase) : new URL("fim/completions", this.apiBase);
Everything else looks perfect, but can this be changed back to what it was before? @AnoyiX

2024-11-22 05:09 UTC, AnoyiX commented on core/llm/llms/OpenAI.ts
> +    const endpoint = this.apiBase?.includes("completions") ? new URL(this.apiBase) : new URL("fim/completions", this.apiBase);
ok, I'll handle it now.

2024-11-27 18:36 UTC, sestinj approved these changes

2024-11-27 21:47 UTC, merged