Adds support for preprompt (systemMessage) on code edition/creation
continuedev/continue pull request #3233
Opened 2024-12-06 19:49 UTC by AnnoyingTechnology

## Description

the `systemMessage` in `config.json` whas only used in pure LLM Chat mode.
When editing code files, or creating code file, this (potentially) crucial context was not injected in the prompt.
This PR inject the systemMessage when editing or creating code too.  

## Checklist

- [x] The relevant docs, if any, have been updated or created

The current documentation states that systemMessage is not used for completion. Which matches the behavior of my PR (and not the existing one).

## Testing

I have tested with a Claude model on Bedrock, but you are invited to try using a different model, since there are different preprompt. I modified both gpt and claude TS files. 

To test, define a systemMessage then just CMD-I/CTRL-I on a new file, check a the prompt that is sent.
Do the same with a CMD-I/CTRL-I of a piece of existing code.

2024-12-06 19:52 UTC, AnnoyingTechnology commented on core/llm/templates/edit/claude.ts
btw, afaik this is not the preffered syntax for talking to claude. If I recall correctly, anthropics recomends using <somePieceOfCode> ... </somePieceOfCode> to describe blocks of code.

2024-12-09 21:54 UTC, sestinj requested changes

2024-12-09 21:54 UTC, sestinj commented on core/llm/templates/edit/claude.ts
> +    // if the LLM has been configured with a systemMessage
I know it may take a bit more shuffling of code, but it's pretty important that the system message be displayed as a system message rather than at the top of the last user message like here

2024-12-11 15:15 UTC, AnnoyingTechnology commented on core/llm/templates/edit/claude.ts
> +    // if the LLM has been configured with a systemMessage
After digging thru the code, I'm not able to figure out how to inject the `systemMessage` at the proper place for edits. It's obvious for the chat mode, but cannot figure it out for edits.

**You'll probably have to do it.**

2024-12-11 19:23 UTC, sestinj commented on core/llm/templates/edit/claude.ts
> +    // if the LLM has been configured with a systemMessage
This is fair enough. I'm sorry this ended up being a temporary dead-end. I'll try to do this in the near future when we revisit loading the system message in general

2024-12-11 19:23 UTC, sestinj commented on core/llm/templates/edit/claude.ts
> +    // if the LLM has been configured with a systemMessage
Thanks for pointing this out anyway, and making the attempt to solve

2024-12-11 19:23 UTC, closed without merging